#!/usr/bin/env node
/**
 * Interactive setup wizard
 * Usage: node scripts/setup.js
 */
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise(resolve => rl.question(q, resolve));

const envPath = path.join(__dirname, '../.env');
const examplePath = path.join(__dirname, '../.env.example');

async function setup() {
  console.log('\n🤖 Dropship AI — Setup Wizard\n' + '═'.repeat(40));

  if (fs.existsSync(envPath)) {
    const overwrite = await ask('\n⚠️  .env already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Setup cancelled. Your existing .env was not changed.\n');
      rl.close(); return;
    }
  }

  console.log('\nAnswer the prompts below. Press Enter to use the [default].\n');

  // ── AI Provider ────────────────────────────────────────
  console.log('━━━ AI Provider ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  const providerChoice = await ask('AI Provider — grok (free) or claude (paid) [grok]: ');
  const provider = providerChoice.trim() || 'grok';

  let grokKey = '', grokModel = '', claudeKey = '', claudeModel = '';
  if (provider === 'grok') {
    grokKey = await ask('Grok API Key (from console.x.ai): ');
    grokModel = (await ask('Grok model [grok-3]: ')).trim() || 'grok-3';
  } else {
    claudeKey = await ask('Anthropic API Key (from console.anthropic.com): ');
    claudeModel = (await ask('Claude model [claude-sonnet-4-20250514]: ')).trim() || 'claude-sonnet-4-20250514';
  }

  // ── Shopify ────────────────────────────────────────────
  console.log('\n━━━ Shopify ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  const shopName = await ask('Shopify store URL (e.g. your-store.myshopify.com): ');
  const accessToken = await ask('Shopify Access Token (shpat_...): ');
  const webhookSecret = await ask('Shopify Webhook Secret (optional, press Enter to skip): ');

  // ── Suppliers ──────────────────────────────────────────
  console.log('\n━━━ Suppliers (optional — press Enter to skip) ━━━━━━━');
  const aliKey = await ask('AliExpress App Key: ');
  const aliSecret = await ask('AliExpress App Secret: ');
  const cjKey = await ask('CJ Dropshipping API Key: ');
  const cjEmail = await ask('CJ Dropshipping Email: ');

  // ── Settings ───────────────────────────────────────────
  console.log('\n━━━ Store Settings ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  const markup = (await ask('Default markup % [200]: ')).trim() || '200';
  const minMargin = (await ask('Minimum profit margin % [30]: ')).trim() || '30';
  const autoFulfill = (await ask('Auto-fulfill orders? (true/false) [true]: ')).trim() || 'true';
  const autoPublish = (await ask('Auto-publish new products? (true/false) [false]: ')).trim() || 'false';
  const baseUrl = await ask('Server base URL for webhooks (e.g. https://your-domain.com, optional): ');
  const port = (await ask('Server port [3000]: ')).trim() || '3000';

  // ── Write .env ─────────────────────────────────────────
  const envContent = `# Generated by setup wizard — ${new Date().toISOString()}

# ============================================
# SHOPIFY
# ============================================
SHOPIFY_SHOP_NAME=${shopName.trim()}
SHOPIFY_ACCESS_TOKEN=${accessToken.trim()}
SHOPIFY_WEBHOOK_SECRET=${webhookSecret.trim()}

# ============================================
# AI PROVIDER: ${provider}
# ============================================
AI_PROVIDER=${provider}
GROK_API_KEY=${grokKey.trim()}
GROK_MODEL=${grokModel}
ANTHROPIC_API_KEY=${claudeKey.trim()}
CLAUDE_MODEL=${claudeModel}

# ============================================
# SUPPLIERS
# ============================================
ALIEXPRESS_APP_KEY=${aliKey.trim()}
ALIEXPRESS_APP_SECRET=${aliSecret.trim()}
CJ_API_KEY=${cjKey.trim()}
CJ_EMAIL=${cjEmail.trim()}

# ============================================
# SERVER
# ============================================
PORT=${port}
NODE_ENV=production
BASE_URL=${baseUrl.trim()}

# ============================================
# PRICING
# ============================================
DEFAULT_MARKUP_PERCENT=${markup}
MIN_PROFIT_MARGIN=${minMargin}
SHIPPING_BUFFER=5
MAX_PRICE_MULTIPLIER=5

# ============================================
# AUTOMATION
# ============================================
AUTO_FULFILL_ORDERS=${autoFulfill}
AUTO_PUBLISH_PRODUCTS=${autoPublish}
MAX_PRODUCTS_PER_RUN=10
PRODUCT_RESEARCH_INTERVAL=6h
PRICE_UPDATE_INTERVAL=1h
INVENTORY_CHECK_INTERVAL=30m
`;

  fs.writeFileSync(envPath, envContent);
  rl.close();

  console.log('\n✅ .env created successfully!');
  console.log('\nNext steps:');
  console.log('  1. npm install');
  console.log('  2. node scripts/validate.js   ← test all connections');
  console.log('  3. npm start                  ← launch server + agents');
  console.log('\n📊 Dashboard: http://localhost:' + port + '\n');
}

setup().catch(err => {
  console.error('Setup failed:', err.message);
  rl.close();
  process.exit(1);
});
